language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- hexo generate
after_success:
- echo ${USER_NAME}
- echo ${USER_EMAIL}
- echo ${GH_TOKEN}
- echo ${GH_REF}
- echo https://${GH_TOKEN}@${GH_REF}
branchs:
  only:
  - dev
env:
  global:
  - USER_NAME="garryshield"
  - USER_EMAIL="749291704@qq.com"
  - REPO="garryshield.github.io"
  - GH_REF="github.com/${USER_NAME}/${REPO}.git"
  - secure: XT2vIpzCyImBuWiJ2BeoUDoIrOYrVI0S/OrFTevoVRrMYZ1XOvLsgF2m175+MQyPi6YZJ4nn6ul+cowru32ltGD73i1H2L512UY/ePlH+FSMfRrxWPvhJZMWQLTT8Xonpd83j0ds7Bl+p/OndtitGcPFF3BN1pinvTgvMdZ5ldidYaq95VN9WJ0UU/Xgzz586Qtm7NDOdfr/zNyOlnf/ci66bbcopKJHZwMmo7akNT5rlxlA+6irmuJqzyjuDpjBFAp6Aj1+ZiRwtEWiZbjJ1Nv8DqpvM2INv7cXis598crvgsMBYfvmQjzWzadFosm6NWSxC3aetuUWPLB8zYJNN/Hm9MjvRtUzQAQUPx/50/cKcxxfjcxGZlCHx2dsThJVcOpX1Q57osSeHie349+yYDYUNkEbSTX7eQhwLlkr0fmUEKVZ+HZyoIYs1vn5gAWfAe16RylBKQAWZEiwvNsgbQiB6VdlFvYglKCrG+ua+ts8ccfqtGlu2mV64eqcOyANOJUKoXzcXQjkZRpEtsW4QmlrzGlru3UibVOvdD7HY2vcP0kH6IKHCc6+UY8xsXIGcTcGNbewKVTcDVBOCMGK2D4dLrTx6EpCsZdqr8gvhgUfHMO4+rn/w7opjrszHpTPERDOeKXEwKe4YM5MzySUCP0VsYfjeB52bsWCo5hFMbk=
