language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- hexo generate
after_success:
- cd public
- git init
- git config user.name "${USER_NAME}"
- git config user.email "${USER_EMAIL}"
- git add .
- git commit -m 'update site'
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branchs:
  only:
  - dev
env:
  global:
  - USER_NAME="garryshield"
  - USER_EMAIL="749291704@qq.com"
  - REPO="garryshield.github.io"
  - GH_REF="github.com/${USER_NAME}/${REPO}.git"
  - secure: o9+w9FpYZRViE/mxXScPC/mdO5Rm2mMfhjQO1ai2yJdu8mbrBTY3QCsF7xAF7FGLCP16rLOz0ZO0c4z+n0CuGlZjwMowzt/gjxjobiJ/UPzlt+SGqNp+bdOyb6QnWIihcuxS7v9ngB2as3InugQgDC65OtpOIMrImHCR6AUtQr5VsTGEka09ZlFaaiReRZ8o7niBVcmxwk0LkukCwJ1ULyOeWJ4nurkkDfVlurDBOo52eXcqTgFGmhB3GFKYAPrwBnbjS84wIWODMFd0ZHuqSC7ZF0H5mrlOv5V5jqeifE1wCyh+qX4KsGgUDwIkbxiS4a/+xyRMKKAe6PnSMZ31SuZzLXDvcHPoriM4ZtJdqpr4eTwSbkoN+jNMPgtIP9Ua/rpBweCUR9pGzyGNE/D+Zu8ILc4NC3AXNeddGjEP0wg0uB0lUhHO9+HWjH1KsylC/y3L+e7vSxbafyqXR4hOPYJahJWs2uiM+/i/fXYbKCUV6WCuSs89mwBXqayYzA7N2ev5rX66P5ftkFDPiXsJ7dTHVuFnu5uRfm+0D+px5WvGLh0vSjs5Or3JQeDFQLC4SdMlBqFTDxFFpsZSbTqJY+0ali5PhQ3esTD9yAQsN5n9ZNwX6jyDKabj4Zu08ViBr1/3JN1sNorLOagJXNR2px82HKSLX2ZIVRBS0sGyOuU=
